// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxsCZWVUCvv61GkVkVSzFPcp7HZl0cSBc',
    appId: '1:507830504707:web:332b980e7e02cf6f3d2d36',
    messagingSenderId: '507830504707',
    projectId: 'finanzasgt-21815',
    authDomain: 'finanzasgt-21815.firebaseapp.com',
    storageBucket: 'finanzasgt-21815.firebasestorage.app',
    measurementId: 'G-E6HPCN56W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNTNRw7TtlZnHd9cceUDpcYulNeBJM9wQ',
    appId: '1:507830504707:android:c7d8dc7183a2fa263d2d36',
    messagingSenderId: '507830504707',
    projectId: 'finanzasgt-21815',
    storageBucket: 'finanzasgt-21815.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfRpa1XBqUz74imy50YCUwiNfPHRvLiEk',
    appId: '1:507830504707:ios:5c1b65f5c555109b3d2d36',
    messagingSenderId: '507830504707',
    projectId: 'finanzasgt-21815',
    storageBucket: 'finanzasgt-21815.firebasestorage.app',
    iosBundleId: 'com.example.finanzagt',
  );
}
